version: '3'
services:
       earthchip: 
           restart: always
           build: .
           image: 'earthchip-mqtt'
           container_name: 'earthchip'         
           ports:
             - "3010:3010"
